# M2608.001300 Machine Learning <br> Assignment #1-1 Python Basics

Copyright (C) Data Science and Artificial Intelligence Laboratory, Seoul National University. This material is for educational uses only. Some contents are based on the material provided by other paper/book authors and may be copyrighted by them. Written by Seil Lee, March 2018

**Note**: certain details are missing or ambiguous on purpose, in order to test your knowledge on the related materials. However, if you really feel that something essential is missing and cannot proceed to the next step, then contact the teaching staff with clear description of your problem.

### Submitting your work:
<font color=red>**DO NOT clear the final outputs**</font> so that TAs can grade both your code and results.  
Once you have done **all parts**, run the *CollectSubmission.sh* script with your **student_id** as input argument. <br>
This will produce a zipped file called *[student_id].zip*. Please submit this file on ETL. &nbsp;&nbsp; (Usage: ./*CollectSubmission.sh* &nbsp; student_id)

---
## 1. Hello, world
The starting point of all programming languages

In [2]:
print('Hello, world!')
print("Hello, world!")

print('Hello,' , 'world!')
print('Hello,' + ' ' + 'world!')

Hello, world!
Hello, world!
Hello, world!
Hello, world!


---
## 2. List and dictionary
### 2.1 List
- Creation

In [3]:
myList_1 = [1,2,3,4,5]
myList_2 = 'A string is also a list'
# Empty lists
myList_3 = []
myList_4 = list()

print(myList_1)
print(myList_2)
print(myList_3)
print(len(myList_1))

[1, 2, 3, 4, 5]
A string is also a list
[]
5


- Merging and indexing

In [4]:
myList_3 = myList_1 + [6,7,8,9,10]
myList_4 = myList_2[4:8]

print(myList_3)
print(myList_3[0])
print(myList_3[-1])
print(myList_4)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
10
ring


### 2.2 Dictionary
- Creation

In [5]:
myDict_1 = {'key_a':'value_1', 'key_b':'value_2'}
myDict_2 = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
# Empty Dictionaies
myDict_3 = {}
myDict_4 = dict()

- Usage

In [6]:
myDict_1['key_c']='value_3'
print(myDict_1.keys())
print(myDict_2.values())
print(myDict_1['key_c'])
print(myDict_2['c'])

dict_keys(['key_a', 'key_b', 'key_c'])
dict_values([1, 2, 3, 4, 5])
value_3
3


***
## 3. Loops/control flow and indentation
### 3.1 For loop

In [7]:
print('The 1st for-loop:')
for eachone in myList_1:
    print(eachone)

print()
print('The 2nd for-loop:')
for i in range(len(myList_1)):
    print(myList_1[i])

# List comprehension
squreOfEachone = [one*one for one in myList_1]

print()
print('The 3rd for-loop:')
for eachone in squreOfEachone:
    print(eachone)

The 1st for-loop:
1
2
3
4
5

The 2nd for-loop:
1
2
3
4
5

The 3rd for-loop:
1
4
9
16
25


### 3.2 If statements

In [8]:
if (True) :
    print('True case')
else:
    print('False case')

print()
for i in range(1,100):
    print(str(i)+':',end='')
    if i % 2 == 0:
        print('EVEN')
    elif i % 2 == 1:
        print('ODD')
    if i == 10:
        break
    else:
        continue

True case

1:ODD
2:EVEN
3:ODD
4:EVEN
5:ODD
6:EVEN
7:ODD
8:EVEN
9:ODD
10:EVEN


---
## 4. Functions
- Defining a function

In [9]:
def printList(theList):
    for one in theList:
        print(one, end=' ')
    print()

def mySqr(n):
    return n*n

def sqrList(l):
    return [i*i for i in l]

- Calling a function

In [10]:
printList(myList_1)
printList([mySqr(i) for i in myList_1])
printList(sqrList(myList_1))

1 2 3 4 5 
1 4 9 16 25 
1 4 9 16 25 


---
## 5. Class
- Defining a class

In [11]:
class Circle :
    pi = 3.141592
    def __init__(self, radius):
        self.radius = radius
    def setRadius(self,r):
        self.radius = r
    def getRadius(self):
        return self.radius
    def getArea(self):
        area = self.radius*self.radius*Circle.pi
        return area

- References a object

In [12]:
a = Circle(10)
b = Circle(1)
print(a.getRadius())
print(a.getArea())
print(b.getRadius())
print(b.getArea())

10
314.1592
1
3.141592


---
## 6. Numpy array
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html
- Creation

In [13]:
import numpy as np
print('ones(5):', np.ones(5))
print('zeros(5):', np.zeros(5))
print('zeros(5, dtype=np.int32):',\
      np.zeros(5, dtype=np.int32)) 
print('arange(5):', np.arange(5))
print('arange(5.):', np.arange(5.),\
      'Type:', np.arange(5.).dtype)

ones(5): [1. 1. 1. 1. 1.]
zeros(5): [0. 0. 0. 0. 0.]
zeros(5, dtype=np.int32): [0 0 0 0 0]
arange(5): [0 1 2 3 4]
arange(5.): [0. 1. 2. 3. 4.] Type: float64


In [14]:
import numpy as np
print('linspace(0,1,5):', np.linspace(0,1,5))
print('random.uniform(size=3):',\
      np.random.uniform(size=3))
print('myList_1:', np.array(myList_1),\
      'Type:', np.array(myList_1).dtype)
x2 = np.tile(np.linspace(0,1,5), (2,1))
print(x2)
print(np.ravel(x2))

linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]
random.uniform(size=3): [0.27542895 0.10489086 0.66048499]
myList_1: [1 2 3 4 5] Type: int64
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.  ]


- Matrix and indexing

In [15]:
x = np.arange(1,11)
print('dim. of x:',x.ndim)
xx = x.reshape((1,-1))
print('dim. of xx:', xx.ndim)
print('----------------')
print('xx:')
print(xx)
print('Transposed xx:')
print(xx.T)
# Dot product
print('----------------')
print('Matrix multiply:')
print('np.dot:')
print(np.dot(xx, xx.T))
print('np.matmul:')
print(np.matmul(xx, xx.T))
print('@ operator:')
print(xx@xx.T)
# Element-wise operation
print('----------------')
print('Element-wise:')
print(xx*xx)
# Broadcasting
print('----------------')
print('Broadcasting:')
print(xx*xx.T)
# Indexing
print('----------------')
print('Indexing:')
mm = xx*xx.T
print(mm[3,3])
print(mm[3:7,3:7])
print(mm[:,-1])
print(mm[1,:])

dim. of x: 1
dim. of xx: 2
----------------
xx:
[[ 1  2  3  4  5  6  7  8  9 10]]
Transposed xx:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
----------------
Matrix multiply:
np.dot:
[[385]]
np.matmul:
[[385]]
@ operator:
[[385]]
----------------
Element-wise:
[[  1   4   9  16  25  36  49  64  81 100]]
----------------
Broadcasting:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
----------------
Indexing:
16
[[16 20 24 28]
 [20 25 30 35]
 [24 30 36 42]
 [28 35 42 49]]
[ 10  20  30  40  50  60  70  80  90 100]
[ 2  4  6  8 10 12 14 16 18 20]


- Merging

In [16]:
print('vstack:')
yy = np.vstack((xx, xx))
print(yy)
print('shape :', yy.shape)
print('hstack:')
print(np.hstack((yy,[[11],[11]])))
zz = np.concatenate((xx,xx), axis=0)
print(zz)
print(yy==zz)

vstack:
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
shape : (2, 10)
hstack:
[[ 1  2  3  4  5  6  7  8  9 10 11]
 [ 1  2  3  4  5  6  7  8  9 10 11]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


---
## 7. File I/O
- Read/write line by line

In [17]:
fileName = 'FileIO.txt'
try:
    with open(fileName, 'w') as outFile :
        print('Test file',file=outFile)
        print('Hello!',file=outFile)
except IOError as err:
    print('File error: ' + str(err))
print(fileName,':')

try:
    with open(fileName, 'r') as inFile :
        for eachLine in inFile:
            eachLine = eachLine.strip() # remove enter
            print(eachLine)
except IOError as err:
    print('File error: ' + str(err))

FileIO.txt :
Test file
Hello!


### <font color=blue>[Problem #1]</font> (30 points)

**Write your own code below so that the results is identical to the following example.**  
1) Read a file : 'iris.data.txt'  
2) Save numerical data into 'iris.data.npy'  
3) Traslate character strings into numbers(0/1/2) then save the numbers into 'iris.label.npy'

In [19]:
print('----------------')
fileName = 'iris.data.txt'
print(fileName,':')

"""
↑↑↑
You can write your code here.
↓↓↓
"""

try:
    with open(fileName, 'r') as inFile:
        dataList = []
        labelList = []
        for eachLine in inFile:
            eachLine = eachLine.strip()
            fields = eachLine.split(",")
            dataList.append(fields[0:4])
            if fields[4] == 'Iris-setosa':
                labelList.append([0])
            elif fields[4] == 'Iris-versicolor':
                labelList.append([1])
            elif fields[4] == 'Iris-virginica':
                labelList.append([2])
except IOError as err:
    print('File error: ' + str(err))

dataNdArray = np.array(dataList, dtype='float64')
labelNdArray = np.array(labelList)
np.save('iris.data.npy', dataNdArray)
np.save('iris.label.npy', labelNdArray)

dataNdArray = np.zeros((4,4))
labelNdArray = np.zeros((1,))
print('Before loading:')
print(dataNdArray)
print(labelNdArray)
dataNdArray = np.load('iris.data.npy')
print('After loading:')
print(dataNdArray[0:10])
labelNdArray = np.load('iris.label.npy')
print(labelNdArray[0:10])

----------------
iris.data.txt :
Before loading:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0.]
After loading:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
